aistores/urls.py
from django.contrib import admin
from django.urls import path, include
from stocks import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^stocks/',include('stocks.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    path('list_items/', views.list_items, name='list_items'),
    path('add_items/', views.add_items, name='add_items'),
    path('update_items/<str:pk>/', views.update_items, name="update_items"),
    path('delete_items/<str:pk>/', views.delete_items, name="delete_items"),
    path('stock_detail/<str:pk>/', views.stock_detail, name="stock_detail"),
    path('issue_items/<str:pk>/', views.issue_items, name="issue_items"),
    path('receive_items/<str:pk>/', views.receive_items, name="receive_items"),
    # path('accounts/', include('registration.backends.default.urls')),
    # path('register/', views.register, name='register'),
    path('', views.home, name='home'),
]

stocks/urls.py
# dappx/urls.py
from django.conf.urls import url
from stocks import views
# SET THE NAMESPACE!
app_name = 'stocks'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

user/urls.py
from django.urls import path
from user.views import signup
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('signup/', signup, name='signup' ),
    path('login/', LoginView.as_view(template_name = 'user/login.html',
                    redirect_authenticated_user = True), name='login'),
    path('logout/', LogoutView.as_view(next_page = 'login'), name='logout'),

]

stocks/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username

class Category(models.Model):
	name = models.CharField(max_length=50, blank=False, null=False)
	def __str__(self):
		return self.name


class Stock(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	item_name = models.CharField(max_length=50, blank=True, null=True)
	quantity = models.IntegerField(default='0', blank=True, null=True)
	receive_quantity = models.IntegerField(default='0', blank=True, null=True)
	receive_by = models.CharField(max_length=50, blank=True, null=True)
	issue_quantity = models.IntegerField(default='0', blank=True, null=True)
	issue_by = models.CharField(max_length=50, blank=True, null=True)
	issue_to = models.CharField(max_length=50, blank=True, null=True)
	phone_number = models.CharField(max_length=50, blank=True, null=True)
	created_by = models.CharField(max_length=50, blank=True, null=True)
	reorder_level = models.IntegerField(default='0', blank=True, null=True)
	last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	export_to_CSV = models.BooleanField(default=False)

	def __str__(self):
		return self.item_name

stocks/forms.py
from django import forms
from .models import Stock
from stocks.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')


class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')


class StockCreateForm(forms.ModelForm):
  class Meta:
    model = Stock
    fields = ['category', 'item_name', 'quantity']

  def clean_category(self):
    category = self.cleaned_data.get('category')
    if not category:
      raise forms.ValidationError('This field is required')
    return category

  def clean_item_name(self):
    item_name = self.cleaned_data.get('item_name')
    if not item_name:
      raise forms.ValidationError('This field is required')

    stocks = Stock.objects.all()
    for instance in stocks:
      if instance.item_name == item_name:
        raise forms.ValidationError(item_name + " exists")
    return item_name


class StockSearchForm(forms.ModelForm):
  class Meta:
    model = Stock
    fields = ['item_name']


class StockUpdateForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['category', 'item_name', 'quantity']


class IssueForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['issue_quantity', 'issue_to']


class ReceiveForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['receive_quantity']

stocks/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Stock
from .forms import *
from stocks.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'stocks/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'stocks/login.html', {})

def home(request):
	title = 'Home'
	context = {
	"header": title,
	}
	return render(request, "stocks/home.html",context)


@login_required
def list_items(request):
	title = 'List of Assets and Consumables'
	form = StockSearchForm(request.POST or None)
	queryset = Stock.objects.all()
	context = {
		"header": title,
		"queryset": queryset,
		"form": form,
	}
	if request.method == 'POST':
		queryset = Stock.objects.filter(
										item_name__icontains=form['item_name'].value()
										)
		context = {
		"form": form,
		"header": title,
		"queryset": queryset,
	}
	return render(request, "stocks/list_items.html", context)

@login_required
def add_items(request):
    form = StockCreateForm(request.POST or None)

    if form.is_valid():
        form.save()
        messages.success(request, 'Successfully Saved')
        return redirect('list_items')
    context = {
		"form": form,
		"header": "Add Asset/Item",
	}
    return render(request, "stocks/add_items.html", context)

@login_required
def update_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = StockUpdateForm(instance=queryset)
	if request.method == 'POST':
		form = StockUpdateForm(request.POST, instance=queryset)
		if form.is_valid():
			form.save()
			messages.success(request, 'Successfully Saved')
			return reverse('list_items')

	context = {
		'form':form
	}
	return render(request, 'stocks/add_items.html', context)

@login_required
def delete_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	if request.method == 'POST':
		queryset.delete()
		messages.success(request, 'Successfully Deleted')
		return reverse('list_items')
	return render(request, 'stocks/delete_items.html')

@login_required
def stock_detail(request, pk):
	queryset = Stock.objects.get(id=pk)
	context = {
		"queryset": queryset,
	}
	return render(request, "stocks/stock_detail.html", context)

@login_required
def issue_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = IssueForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity -= instance.issue_quantity
		# instance.issue_by = str(request.user)
		messages.success(request, "Issued SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name) + "s now left in Store")
		instance.save()

		return redirect('/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": 'Issue ' + str(queryset.item_name),
		"queryset": queryset,
		"form": form,
	    "username": 'Issue By: ' + str(request.user),
	}
	return render(request, "stocks/add_items.html", context)

@login_required
def receive_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = ReceiveForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity += instance.receive_quantity
		instance.save()
		messages.success(request, "Received SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name)+"s now in Store")

		return redirect('/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": 'Reaceive ' + str(queryset.item_name),
			"instance": queryset,
			"form": form,
			"username": 'Receive By: ' + str(request.user),
		}
	return render(request, "stocks/add_items.html", context)

stocks/templates/stocks/add_items.html
{% extends 'main/base_0.html' %}
{% debug %}
<!--Block content goes below-->
{% load crispy_forms_tags %}



{% block content %}
{% include 'navbar.html' %}
  <main role="main" class="container">
    <div class="jumbotron">
      <h1>{{header}}</h1>

      <form method='POST' action=''>{% csrf_token %}
        {{form|crispy}}
        <input type="submit" value='Save'/>
      </form>

    </div>
  </main>


  {% endblock %}

stocks/templates/stocks/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    {% include 'navbar.html' %}
    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">

        <ul class="nav navbar-nav">
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'stocks:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

stocks/templates/stocks/base_old.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->



  {% include 'navbar.html' %}

  {% block content %}
  {% endblock %}

stocks/templates/stocks/delete_items.html
{% extends 'main/base_0.html' %}

<!--Block content goes below-->

{% block content %}
{% include 'navbar.html' %}
  <main role="main" class="container">
    {% if messages %}
          <ul class="messages">
                 {% for message in messages %}
                       <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                 {% endfor %}
         </ul>
    {% endif %}
    <div class="jumbotron">
      <h1>{{header}}</h1>

      <form method="post" action="">
        {% csrf_token %}
          <h1>Are you sure you want to delete?</h1><br>
          <input class="btn btn-danger" type="submit" value="Yes" />
          <a href="/list_items"><div class="btn btn-primary">Cancel</div></a>
     </form>

    </div>
  </main>


  {% endblock %}

stocks/templates/stocks/home.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->


  {% block content %}
  <img src="{% static 'img/ais-stores2.jpg'  %}" alt="Landing Page">
  {% endblock %}

stocks/templates/stocks/index.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->


  {% block content %}
  <img src="{% static 'img/ais-stores2.jpg'  %}" alt="Landing Page">
  {% endblock %}

stocks/templates/stocks/list_items.html
{% extends 'main/base_0.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<!--Block content goes below-->

{% block extra_head %}
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
{% endblock%}
{% block content %}

{% include 'navbar.html' %}
<main role="main" class="container">
  {% if messages %}
        <ul class="messages">
               {% for message in messages %}
                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
               {% endfor %}
       </ul>
  {% endif %}
    <div class="jumbotron">
      <div class="header">
          {{header}}
        </div>
        <form method='POST' action=''>{% csrf_token %}
            {{form|crispy}}
                <input type="submit" value='Search'/>
        </form>
        <br>
      <div class="display_table">
        <table class='table'>
            <thead>
            <tr>
                <th>SR.NO</th>
                <th>CATEGORY</th>
                <th>ITEM NAME</th>
                <th>QUANTITY IN STORE</th>
                <th>TIMESTAMP</th>
                <th>LAST UPDATED</th>
                <th>DELETE</th>
            </tr>
            </thead>
            {% for instance in queryset %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{instance.category}}</td>
                    <td><a href="{% url 'update_items' instance.id %}">{{instance.item_name}}</a></td>
                    <td><a href="{% url 'stock_detail' instance.id %}">{{instance.quantity}}</a></td>
                    <td>{{instance.timestamp}}</td>
                    <td>{{instance.last_updated}}</td>
                    <td><a href="{% url 'delete_items' instance.id %}">
                            <!-- <i class="fa fa-trash-o" aria-hidden="true"></i> -->
                            Delete
                        </a>
                    </td>
                </tr>

            {% endfor %}
        </table>
    </div>

    </div>
  </main>



{% endblock %}

stocks/templates/stocks/login.html
{% extends 'main/base_0.html' %}
{% load static %}

{% block content %}



      	<div class="d-flex justify-content-center h-100">
      		<div class="card">
      			<div class="card-header">
      				<h3>AIS Sign In</h3>
      				<div class="d-flex justify-content-end social_icon">
      					<span><i class="fab fa-facebook-square"></i></span>
      					<span><i class="fab fa-google-plus-square"></i></span>
      					<span><i class="fab fa-twitter-square"></i></span>
      				</div>
      			</div>
      			<div class="card-body">
              <form method="post" action="{% url 'stocks:user_login' %}" >
              {% csrf_token %}
      					<div class="input-group form-group">
      						<div class="input-group-prepend">
      							<span class="input-group-text"><i class="fas fa-user"></i></span>
      						</div>
      						<input type="text" class="form-control" name="username" placeholder="username">

      					</div>
      					<div class="input-group form-group">
      						<div class="input-group-prepend">
      							<span class="input-group-text"><i class="fas fa-key"></i></span>
      						</div>
      						<input type="password" class="form-control" name="password"  placeholder="password">
      					</div>
      					<!-- <div class="row align-items-center remember">
      						<input type="checkbox">Remember Me
      					</div> -->
      					<div class="form-group">
      						<input type="submit" value="Login" class="btn float-right login_btn">
      					</div>
      				</form>
      			</div>
      			<div class="card-footer">
      				<!-- <div class="d-flex justify-content-center links">
      					Don't have an account?<a href="#">Sign Up</a>
      				</div>
      				<div class="d-flex justify-content-center">
      					<a href="#">Forgot your password?</a>
      				</div> -->
      			</div>
      		</div>
      	</div>

{% endblock content %}

stocks/templates/stocks/register.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->


<div class="container">
{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form }}
  </form>
  if you already have an account <a href="/login">login</a> instead.
{% endblock %}
</div>

stocks/templates/stocks/registration.html
{% extends "stocks/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

stocks/templates/stocks/stock_detail.html
{% extends 'main/base_0.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<!--Block content goes below-->

{% block extra_head %}
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
{% endblock%}
{% block content %}

{% include 'navbar.html' %}
<main role="main" class="container">
    <div class="jumbotron">
      <div class="header">
          {{header}}
        </div>

        <br>
        <a href="{% url 'issue_items' queryset.id %}"><div class='btn btn-danger'>ISSUE THIS ITEM</div></a>
        <a href="{% url 'receive_items' queryset.id %}"><div class='btn btn-primary'>RECEIVE THIS ITEM</div></a>

          <br><br>
          <div class="display_table">
            <table class='table'>
                    <tr>
                      <th>ITEM NAME</th>
                      <th>QUANTITY IN STORE</th>
                      <th>LAST UPDATED</th>
                      <th>REORDER LEVEL</th>
                    </tr>
                    <tr>
                      <td>{{queryset.item_name}}</td>
                      <td>{{queryset.quantity}}</td>
                      <td>{{queryset.last_updated}}</td>
                      <td>{{queryset.reorder_level}}</td>
                    </tr>
            </table>
          </div>

    </div>
  </main>



{% endblock %}